### ISSUE TITLE
Connection Problems

### ISSUE THREAD

**Issue by antonilo** [unitreerobotics/unitree_ros_to_real#17]
Hi, 

I am having problem setting up the connection to the robot in ROS. My goal is to run offboard computation on my PC from on-board data (real sense images). Now I can't send messages from my computer to the robot using ROS. I have followed [this guide](http://wiki.ros.org/ROS/NetworkSetup)  and I can send messages from the robot to my PC (for example images from the realsense). However, I cannot send messages from the computer to the robot. I am not sure how to run the net connection setup in the readme. Where should I run it, on my computer or on the robot?

Thanks in advance!

**Comment by itaouil** [comment]
Ciao Antonio,

What is your network setup? Are you connected to the robot via ethernet or wifi?

Also, two have a two-way communication from PC to Robot and vice-versa you have to:

1. Add IP of the robot in the known hosts of the PC (in /etc)
2. Add IP of the PC to the known hosts of the Robot (in /etc)
3. Export ROS_HOSTNAME and ROS_IP in both the PC and the Robot (create an alias so you can run it when you need it via **bashrc**)

The ROS_HOSTNAME is always something like this: http://<ip_of_the_machine_running_ros_master>::11311 whereas the ROS_IP is the IP of the respective machine (for the robot the robot_ip and for the PC the pc_ip).

I have a WIFI network setup, so both the PC and Robot are connected to the same network, and by doing the above I got it to work both ways.

P.S: We have an AlienGo, and the built-in WIFI card reception was terrible so I had to use a WIFI dongle to get a better signal. I assume that is because the built-in card is inside the Alumunium body frame which does not help.

Hope it helps :)

In bocca al lupo!

**Comment by antonilo** [comment]
Thanks a lot @itaouil! I have an A1, do you know if anything different is required on the A1 for establishing two-way communications over wifi? I have now managed to do it over ethernet, but that is not so convenient for a mobile robot :)
Out of curiosity: Which wifi dongle are you using?

**Comment by itaouil** [comment]
I would say it should be the same. I used this two-way communication setup with all sorts of robots and it was always the same :).

Oh, I have no idea. I can check for you next time I am in the lab. 

But I had to use an old wifi dongle, as newer ones had driver problems with the on-board PC of our AlienGo (it is still running Ubuntu 16.04 and we can't upgrade it yet as it may break something).

**Comment by antonilo** [comment]
Thanks! I have also used it on many other robots but it does not (yet) work on the A1 (I guess some fancy networking is happening there). I would be happy to know which model it is, I might get the same one :-1:

**Comment by itaouil** [comment]
Sure will let you know :)

Did you switch to a WIFI setup now? Or you are still trying to get it to work via ethernet?

I am happy to help with my 2 cents in case, although I never tried the ethernet communication setup with the AlienGo before.

**Comment by antonilo** [comment]
Ethernet already works but it is not scalable. I need to get it running on the wifi :) That's why I would be glad to know which wifi dongle is compatible with the ubuntu 16 running onboard :)

**Comment by antonilo** [comment]
@ZKBian any idea on how to get it running using the A1 wifi?

**Comment by itaouil** [comment]
Sure will let you know tomorrow.

But the internal Wi-Fi should also work it is just that reception is low, nonetheless I was still able to visualize topics with Rviz coming from the robot.

**Comment by staycoolish** [comment]
I am trying to control A1 using wifi, but there is no information about that. If you achieved this, it would be nice if you can explain how to do it...
